### ISSUE TITLE
How to connect to FTPS (FTP with TLS AUTH)

### ISSUE THREAD

**Issue by maha-haji** [IndustrialShields/arduino-FTP#1]
Hi,

Is it possible to use this library to connect to an FTP server using TLS AUTH? Additionally, can I use WiFiClient() or WiFiSSLClient() instead of EthernetClient()? 

Thank you!

**Comment by jordicasals** [comment]
Hi maha-haji,

first of all, thank you for using this library!

The library accepts a couple of Client objects, so, you should be able to use both WiFiClient and WiFiSSLClient. I think that they inherit from Client.

Best regards,

**Comment by maha-haji** [comment]
Thanks for the quick reply! Yes, I see I was able to try any of those clients, however I get an error when trying to connect to the FTPS. Namely, when I use WiFiClient(), as soon as I am connected it says "530 Non-anonymous sessions must use encryption." and then I am disconnected. Changing to WiFiSSLClient() does not work and I am not able to connect period. Any thoughts on how I should proceed?

**Comment by maha-haji** [comment]
Hi- I have since gotten the code to run through with no errors, but the file I have is not ultimately written to the FTP server. Serial monitor says:
"You have 10 seconds to write something...
The written content is sent to the FTP file"

As mentioned, I am wondering if the issue has something to do with the need to connect via FTPS instead of FTP?

**Comment by jordicasals** [comment]
Hi maha-haji,

I suppose that you are using the "store" example as it is, using the WiFiSSLClient instead of EthernetClient. I this case, you could check the return status of the store function:
```c++
int storeRet = ftp.store(fileName, Serial);
if (storeRet == 0) {
  Serial.println("Store error");
  while (true);
}
```

I also suppose that you are typing some data using the Serial Monitor when the "You have 10 seconds to write something..." message is shown. This is the time you have to fill up the Serial buffer with some data.

In case you are using another sketch, could you please send it? Please, remember to remove private information.

**Comment by maha-haji** [comment]
Hi,

Thanks for the help. I did try inputting those lines of code and received the "Store error" response. Here's my sketch below. Do you have thoughts as to what I might be doing wrong? 

Thanks!


```
#include <WiFi101.h>
#include <SD.h>
#include <SPI.h>
#include <FTP.h>

const int chipSelect = 4;
char ssid[] = "WIFISSID";        // your network SSID (name)
char wifipass[] = "WIFIPASS";    // your network password (use for WPA, or use as key for WEP)
int status = WL_IDLE_STATUS;     // the Wifi radio's status

// change to your server
char server[] = "server.server.com";    // name address for FTP server
const char *user = "FTPUSER";
const char *pass = "FTPPASS";
const char *fileName = "FTP0001.CSV";

WiFiClient ftpControl;
WiFiClient ftpData;

FTP ftp(ftpControl, ftpData);

////////////////////////////////////////////////////////////////////////////////////////////////////
void setup() {
  //Initialize serial and wait for port to open:
  Serial.begin(9600UL); 
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  
  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present"); 
    // don't continue:
    while(true);
  } 
  
// attempt to connect to Wifi network:
  while ( status != WL_CONNECTED) { 
    Serial.print("Attempting to connect to WPA SSID: ");
    Serial.println(ssid);

    // Connect to WPA/WPA2 network:    
    status = WiFi.begin(ssid, wifipass);
    // wait 10 seconds for connection:
    delay(10000);
    // you're connected now, so print out the data:
    Serial.print("You're connected to the network ");
    printCurrentNet();
    printWifiData();
  
    if (!ftp.connect(server, 21, user, pass) == 0) {
        Serial.println("Error connecting to FTP server");
        while (true);
    }
  
    Serial.println("You have 10 seconds to write something...");
    delay(10000UL);

    // Send the written content to the FTP file
    int storeRet = ftp.store(fileName, Serial);
    if (storeRet == 0) {
      Serial.println("Store error");
      while (true);
     }

    Serial.println("The written content is sent to the FTP file");
  }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
void loop() {
  // Nothing to do
}

void printWifiData() {
  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
    Serial.print("IP Address: ");
  Serial.println(ip);
    
  // print your MAC address:
  byte mac[6];  
  WiFi.macAddress(mac);
  Serial.print("MAC address: ");
  Serial.print(mac[5],HEX);
  Serial.print(":");
  Serial.print(mac[4],HEX);
  Serial.print(":");
  Serial.print(mac[3],HEX);
  Serial.print(":");
  Serial.print(mac[2],HEX);
  Serial.print(":");
  Serial.print(mac[1],HEX);
  Serial.print(":");
  Serial.println(mac[0],HEX);

}

void printCurrentNet() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print the MAC address of the router you're attached to:
  byte bssid[6];
  WiFi.BSSID(bssid);    
  Serial.print("BSSID: ");
  Serial.print(bssid[5],HEX);
  Serial.print(":");
  Serial.print(bssid[4],HEX);
  Serial.print(":");
  Serial.print(bssid[3],HEX);
  Serial.print(":");
  Serial.print(bssid[2],HEX);
  Serial.print(":");
  Serial.print(bssid[1],HEX);
  Serial.print(":");
  Serial.println(bssid[0],HEX);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.println(rssi);

  // print the encryption type:
  byte encryption = WiFi.encryptionType();
  Serial.print("Encryption Type:");
  Serial.println(encryption,HEX);
  Serial.println();
}

void printWiFiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}
```

**Comment by maha-haji** [comment]
I think I see the problem. I added the following lines of code:
`int connectRet = ftp.connect(server,21, user, pass);
    Serial.println(connectRet);`

And I see that connectRet = 0, meaning the ftp did not successfully connect. I am able to connect using a client like cyberduck, but require using FTP-SSL (Explicit AUTH TLS). Do you know if I need to be doing something different in my code?

**Comment by jordicasals** [comment]
I see.

The WiFi101 library requires a connectSSL method to connect to a server using TLS. You could manage the control socket connection with the ftpControl.connectSSL() method, and then using the ftp.auth() method to authenticate.
The data socket is managed by the library, and it uses de connect() method, so, I supose you will have the same problem.

We will look for the best approach as soon as possible.

**Comment by maha-haji** [comment]
Thanks for the thoughts. I have changed my setup and am now going through Ethernet only with an Ethernet shield (WiFi shield I think has issues of accessing SD card simultaneously with internet so I switched). I am using the standard "Store" example (see code below) but I get the error "Error connecting to FTP server." How can I go about editing this code using the methods you describe above for trying to get the SSL going?

```
#include <SD.h>
#include <SPI.h>
#include <FTP.h>

#if defined(MDUINO_PLUS)
#include <Ethernet2.h>
#else
#include <Ethernet.h>
#endif

const int chipSelect = 4;

// this must be unique
byte mac[] = { 0x90, 0xA2, 0xDA, 0x00, 0x59, 0x67 };  

// change to your network settings
IPAddress ip( 192, 168, 1, 4 );  
IPAddress namesServer( 192, 168, 1, 1 );  
IPAddress gateway( 192, 168, 1, 1 );
IPAddress netmask( 255, 255, 255, 0 );

// change to your server
//IPAddress server( 1, 2, 3, 4 );
char server[] = "server.server.com";    // name address for FTP server
const char *user = "FTPUSER";
const char *pass = "FTPPASS";
const char *fileName = "FTP0001.CSV";

EthernetClient ftpControl;
EthernetClient ftpData;

FTP ftp(ftpControl, ftpData);

////////////////////////////////////////////////////////////////////////////////////////////////////
void setup() {
  Serial.begin(9600UL);

  Ethernet.begin(mac, ip, namesServer, gateway, netmask);
  Serial.print("IP address: ");
  Serial.println(Ethernet.localIP());

  if (!ftp.connect(server, user, pass)) {
    Serial.println("Error connecting to FTP server");
    while (true);
  }

  Serial.println("You have 10 seconds to write something...");
  delay(10000UL);

  // Send the written content to the FTP file
  ftp.store(fileName, Serial);

  Serial.println("The written content is sent to the FTP file");
}

////////////////////////////////////////////////////////////////////////////////////////////////////
void loop() {
  // Nothing to do
}

```

**Comment by jordicasals** [comment]
The Ethernet Shield does not support SSL/TLS, due to an encryption chip is needed (ATECC608).

**Comment by maha-haji** [comment]
Thank you. So it sounds like the WiFi shield would be the only possibility, but that might have the issue of not being able to access the SD card at the same time as being connected to the FTP server?
