### ISSUE TITLE
Error compiling for MKR boards

### ISSUE THREAD

**Issue by heshan4nando** [IndustrialShields/arduino-FTP#2]
I am trying to use this library with an MKR boards (version 1.8.12); however, the example code does not compile. They compile without issues for AVR boards. The error that I get for MKR boards is an "invalid type conversion from 'char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive] in FTP.cpp:274:33. Is there an easy fix for this? Thanks!

**Comment by jordicasals** [comment]
Dear @heshan4nando 

It should be secure to replace the line 274 of the src/FTP.cpp file with:
`buffLen += cClient.read((uint8_t*) (buff + buffLen), len);`

**Comment by heshan4nando** [comment]
Perfect! Thank you! I thought it should be a simple fix like that.
